FROM node:16

WORKDIR /app

# Enable corepack for yarn
RUN corepack enable

# Copy package.json for layer caching
COPY package.json yarn.lock ./
RUN yarn install

# Start dev server
CMD ["yarn", "start"]
